on:
  push:
    branches:
      - master
name: Update Docs
jobs:
  updateDocs:
    name: Export Website Static HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Next Export
        run: yarn run export
    
      - name: Push to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: ./out
          full_commit_message: Export HTML for ${{ github.event.head_commit.id }}